//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEFDBFirst1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Eid { get; set; }
        public string Ename { get; set; }
        public string Job { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Department Department1 { get; set; }
    }
}
